### ISSUE TITLE
Constitution is not present in system ABI file

### ISSUE THREAD

**Issue by thomasbcox** [EOS-Mainnet/eos#25]
The current System ABI file is missing the Constitution in the ricardian clauses section.

**Comment by kesar** [comment]
Constitution is in https://github.com/EOS-Mainnet/eos/tree/launch-rc

Some teams have been using tag 1.0.1 + pulling latest code from https://github.com/EOS-Mainnet/governance

In my opinion, we **shoudnt** merge Constitution ABIs into the source code. The reason is that we will end  up with conflicts between our community mainnet repo and b1 repo, that could lead into bugs and unexpected results.

What I would suggest its to create an eos_mainnet_build.sh in the root of the project that performs (for now):
- Clone Governance repo (that should have tag as well) and move desired documents.
- Compile code with EOS instead of SYS
